### ISSUE TITLE
While sharing an audio expression - took about 10 seconds of loading to share

### ISSUE THREAD

**Issue by yaz38** [juntofoundation/junto-mobile#803] opened 2020-06-03 00:28 UTC

**Comment by Nash0x7E2** [comment] 2020-06-03 23:20
This can be due to network speed, latency, etc. I'll have a look at posting an audio expression to verify it's not something app side.

**Comment by Nash0x7E2** [comment] 2020-06-03 23:21
@yaz38 How long was the audio? The longer the audio the larger the file size which in turn would affect the upload time.

**Comment by yaz38** [comment] 2020-06-03 23:28
1 min 30ish seconds and the other was 2 min

**Comment by Nash0x7E2** [comment] 2020-06-03 23:29
Cool, will try to reproduce :+1

**Comment by Nash0x7E2** [comment] 2020-06-08 15:24
I am closing this for now. After testing, audio expressions are being uploaded within a reasonable time period.

**Closed by Nash0x7E2** 2020-06-08 15:24 UTC
Labels: High Priority, bug
