### ISSUE TITLE
[Cognito] email verification issue

### ISSUE THREAD

**Issue by yaz38** [juntofoundation/junto-mobile#859] opened 2020-06-18 00:09 UTC
after not receiving verification number, I clicked upwards on the signup survey to see if I had typed the correct email,  and when I tried
to go back down to verification number it displayed this image

![image](https://user-images.githubusercontent.com/65966547/84963092-7293cc00-b0d6-11ea-8567-2aa33860a3f8.png)

**Comment by orestesgaolin** [comment] 2020-06-18 08:03
Thanks!

@sunyatax @Nash0x7E2 Here we have one of the edge cases. The issue is that after going to the "verify code" screen the account is actually created on Cognito, but it's not verified yet. My solution for that:

- disable going back on the verify code screen to the email/password screen
- add extra button on the verify screen with _Resend verification code_. We can add simple timer to block tapping it too frequently

The best would be also to check on login if account is verified and if not then we could show proper screen, send verification code and prompt for it.

Let me know if we should proceed with the first two points

**Comment by sunyatax** [comment] 2020-06-18 15:08
Interesting. 

So, for the first solution of disabling going back to the email/password screen, we still have the edge case of someone closing the app and restarting the sign up process. This seems to be an improvement to what we have, but not the entire fix.

Having a resend verification code on the verify screen would be nice. 

Perhaps we could check if an account is verified when they start the sign up process as well? In the case that they are, we could just direct them to the verify screen. @orestesgaolin

**Comment by Nash0x7E2** [comment] 2020-06-23 01:24
Hey 👋 
For the time being, I've implemented #863.

There are three solutions we can implement here:

1. We permanently disable the up button and store the user's information locally on device. The next time the user opens the app, we simply show the verification screen and the first page (with options to go to navigate to the welcome screen). In this scenario, we would also need to resend the verification code whenever the user launches the application. 

2. Instead of disabling the up arrow, we can show a "resend verification" button under the textfield which resends the email. 

3. Implement a combination of 1 & 2. The reason for this is if the user switches the app (maybe to check their email), the OS can kill the app while it is in the background. This would leave the user in a situation where they have their account created but unverified and unable to login. 

In all cases, we also need to cater for cases where the user cancels the process and leaves the account unverified. Since the username and email are reserved at this point, do we remove unverified accounts?  

@orestesgaolin @sunyatax let me know which option you prefer and I can implement it fully in the morning. In the meantime, we can merge #863 as a temporary fix until we have a more long term solution.

**Comment by Nash0x7E2** [comment] 2020-06-23 23:53
@orestesgaolin Unfortunately AWS does not return whether the user account is confirmed or not https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSMobileClient/Enums/UserState.html

**Closed** 2020-06-24 11:42 UTC
Labels: Auth, High Priority
